name: e2e-suite

on:
  pull_request_review:
    types: ['submitted']

jobs:
  e2e-all-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install ginkgo
      run: go get github.com/onsi/ginkgo/ginkgo@v1.16.5

    - name: turn off swap
      run: sudo swapoff -a

    - name: Set netfilter conntrack max
      run: sudo sysctl -w net.netfilter.nf_conntrack_max=131072

    - id: 'reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
    - # Conditionally run the next step
        if: 'steps.reviews.outputs.approved >= 1 && steps.reviews.outputs.changes_requested == 0'
        - name: Run all e2e tests
          run: yes | make test-e2e