name: Push to Harbor

on:
  release:
    # Build and push artifacts when new release is published
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # - name: Login to Harbor Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: projects.registry.vmware.com
      #     username: ${{ secrets.HARBOR_USERNAME }}
      #     password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Controller Image
        run: IMG="projects.registry.vmware.com/cluster_api_provider_bringyourownhost/cluster-api-byoh-controller:${{ github.ref_name }}" make docker-build
      
      - name: Login to Harbor Registry
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login projects.registry.vmware.com -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin ; IMG="projects.registry.vmware.com/cluster_api_provider_bringyourownhost/cluster-api-byoh-controller:${{ github.ref_name }}" make docker-push
