name: Push to Harbor

on:
  release:
    # Build and push artifacts when new release is published
    types: [published]

env:
  REGISTRY: projects.registry.vmware.com
  IMAGE_NAME: cluster_api_provider_bringyourownhost/cluster-api-byoh-controller
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.16

      - name: Login to Harbor Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Build Controller Image
      #   run: IMG="projects.registry.vmware.com/cluster_api_provider_bringyourownhost/cluster-api-byoh-controller:${{ github.ref_name }}" make docker-build
      
      # - name: Login to Harbor Registry
      #   run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login projects.registry.vmware.com -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin ; IMG="projects.registry.vmware.com/cluster_api_provider_bringyourownhost/cluster-api-byoh-controller:${{ github.ref_name }}" make docker-push
